# NumPy Cheat Sheet for Hackathons

This notebook provides a comprehensive overview of the most frequently used NumPy functionalities, tailored for quick reference during a hackathon. It covers array creation, attributes, indexing, and core mathematical operations.

## 1. Importing NumPy

It is a strong convention to import NumPy with the alias `np`.

In [1]:
# Import the numpy library and assign it the conventional alias 'np'
import numpy as np

## 2. Array Creation

There are several ways to create NumPy arrays. The most common methods include creating them from a Python list, or using built-in functions like `arange`, `zeros`, `ones`, and `linspace`.

In [2]:
# Create a 1D array from a Python list
my_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(my_list)
print(f"Array from list: {arr_from_list}")

# Create a 2D array (matrix) from a list of lists
my_2d_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(my_2d_list)
print(f"2D Array:{arr_2d}")

# Create an array with a sequence of numbers using arange()
# np.arange(start, stop, step)
arr_arange = np.arange(0, 10, 2)
print(f"Array from arange: {arr_arange}")

# Create an array of zeros
# np.zeros(shape)
arr_zeros = np.zeros((2, 3)) # A 2x3 matrix of zeros
print(f"Array of zeros:{arr_zeros}")

# Create an array of ones
# np.ones(shape)
arr_ones = np.ones((3, 2)) # A 3x2 matrix of ones
print(f"Array of ones:{arr_ones}")

# Create an array with a specific number of elements between a start and end point
# np.linspace(start, stop, num_elements)
arr_linspace = np.linspace(0, 1, 5) # 5 numbers from 0 to 1 (inclusive)
print(f"Array from linspace: {arr_linspace}")

# Create an array of random floating-point numbers
rng = np.random.default_rng() # Modern random number generator
arr_random = rng.random((2, 2)) # A 2x2 matrix of random floats between 0.0 and 1.0
print(f"Random array:{arr_random}")

Array from list: [1 2 3 4 5]
2D Array:[[1 2 3]
 [4 5 6]]
Array from arange: [0 2 4 6 8]
Array of zeros:[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:[[1. 1.]
 [1. 1.]
 [1. 1.]]
Array from linspace: [0.   0.25 0.5  0.75 1.  ]
Random array:[[0.26477115 0.75178675]
 [0.38327259 0.44753145]]


## 3. Array Attributes

Understanding the attributes of your arrays is crucial for debugging and manipulation. Key attributes include `shape`, `ndim`, `dtype`, `size`, and `itemsize`.

In [3]:
# Create a sample 3x4 array
sample_arr = np.arange(12).reshape(3, 4)
print(f"Sample Array:{sample_arr}")

# Get the shape of the array (number of rows, number of columns)
print(f"Shape: {sample_arr.shape}")

# Get the number of dimensions (axes)
print(f"Number of dimensions: {sample_arr.ndim}")

# Get the data type of the elements
print(f"Data type: {sample_arr.dtype.name}")

# Get the total number of elements in the array
print(f"Total size: {sample_arr.size}")

# Get the size in bytes of each element
print(f"Item size (bytes): {sample_arr.itemsize}")

Sample Array:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Number of dimensions: 2
Data type: int64
Total size: 12
Item size (bytes): 8


## 4. Indexing and Slicing

NumPy offers powerful and flexible ways to access and modify array elements. This includes basic indexing, slicing to get sub-arrays, and advanced boolean and fancy indexing.

In [4]:
# Create a 1D array for demonstration
idx_arr_1d = np.arange(10, 20)
print(f"1D Array: {idx_arr_1d}")

# Basic indexing: Access a single element (0-indexed)
print(f"Element at index 3: {idx_arr_1d[3]}")

# Slicing: Get a range of elements [start:stop:step]
print(f"Elements from index 2 to 5: {idx_arr_1d[2:6]}")

# Create a 2D array
idx_arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:{idx_arr_2d}")

# 2D indexing: Access an element with [row, col]
print(f"Element at row 1, col 2: {idx_arr_2d[1, 2]}")

# 2D slicing: Get a sub-matrix
# Get rows 0 and 1, and columns 1 and 2
print(f"Sub-matrix:{idx_arr_2d[:2, 1:]}")

# Boolean Indexing: Select elements based on a condition
bool_mask = idx_arr_1d > 15
print(f"\nElements greater than 15: {idx_arr_1d[bool_mask]}")

# Fancy Indexing: Pass a list or array of indices
fancy_indices = [1, 4, 7]
print(f"Elements at indices {fancy_indices}: {idx_arr_1d[fancy_indices]}")

1D Array: [10 11 12 13 14 15 16 17 18 19]
Element at index 3: 13
Elements from index 2 to 5: [12 13 14 15]

2D Array:[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
Sub-matrix:[[2 3]
 [5 6]]

Elements greater than 15: [16 17 18 19]
Elements at indices [1, 4, 7]: [11 14 17]


## 5. Array Broadcasting

Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. It allows you to perform operations between arrays of different sizes without making explicit copies of the smaller array.

In [5]:
# Create a 3x3 array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 1D array
b = np.array([1, 0, 1])

# Add the 1D array 'b' to each row of the 2D array 'a'
# NumPy automatically 'broadcasts' or stretches 'b' to match the shape of 'a'
c = a + b

print(f"Array A:{a}")
print(f"Array B: {b}")
print(f"Result of broadcasting A + B:{c}")

Array A:[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array B: [1 0 1]
Result of broadcasting A + B:[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


## 6. Mathematical and Statistical Functions

NumPy provides a vast library of universal functions (`ufuncs`) that perform element-wise operations, as well as aggregation functions for statistical analysis.

In [ ]:
# Create an array for statistical analysis
stats_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Stats Array:{stats_arr}")

# Sum of all elements
print(f"Sum of all elements: {np.sum(stats_arr)}")

# Sum along columns (axis=0)
print(f"Sum of columns: {np.sum(stats_arr, axis=0)}")

# Sum along rows (axis=1)
print(f"Sum of rows: {np.sum(stats_arr, axis=1)}")

# Calculate the mean, standard deviation, and variance
print(f"Mean: {np.mean(stats_arr)}")
print(f"Standard Deviation: {np.std(stats_arr)}")
print(f"Variance: {np.var(stats_arr)}")

# Find the minimum and maximum values
print(f"Minimum value: {np.min(stats_arr)}")
print(f"Maximum value: {np.max(stats_arr)}")

# Find the index of the minimum and maximum values
print(f"Index of min value: {np.argmin(stats_arr)}")
print(f"Index of max value: {np.argmax(stats_arr)}")

# Universal functions (element-wise)
print(f"Array squared:{np.square(stats_arr)}")
print(f"Square root of array:{np.sqrt(stats_arr)}")

Stats Array:[[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]
Mean: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Minimum value: 1
Maximum value: 6
Index of min value: 0
Index of max value: 5
 Array squared:[[ 1  4  9]
 [16 25 36]]
Square root of array:[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
